# ==============================================================================
[nixbox]

# ------------------------------------------------------------------------------
# Error: "/etc/os-release" could not be found on container nixbox: no such file or directory
# 로 중단했다.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
image=docker.io/nixos/nix:latest

init=false
pull=true
start_now=true
additional_flags="--entrypoint /nix/var/nix/profiles/default/bin/nix-shell"
# NixOS는 초기 설정에 시간이 걸릴 수 있으므로 초기화 명령어를 추가할 수 있습니다.
init_command="nix-channel --update && nix-env -iA nixpkgs.bashInteractive nixpkgs.coreutils"
# pre_init_hooks=""
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
additional_packages="autokey"
exported_apps="autokey-gtk"
# exported_apps="autokey-gtk"
# exported_apps="autokey-gtk"

additional_packages="redshift geoclue2"
exported_apps="redshift-gtk"

additional_packages="firejail"
# exported_apps=""

additional_packages="timeshift"
exported_apps="timeshift"
# exported_apps="timeshif-gtk"
# exported_apps="timeshift-launcher"

additional_packages="gnome-disk-utility"
exported_apps="gnome-disks"

additional_packages="gnome-keyring"
# exported_apps="gnome-keyring"
# exported_apps="gnome-keyring-3"
# exported_apps="gnome-keyring-daemon"

# 확인해야 한다.
additional_packages="vscode"
exported_apps="vscode"

additional_packages="doublecmd"
exported_apps="doublecmd"

#
additional_packages="google-chrome"
exported_apps="google-chrome-stable"

additional_packages="firefox"
exported_apps="firefox"

additional_packages="remmina"
exported_apps="remmina"
# exported_apps="remmina-file-wrapper"

additional_packages="libreoffice"
exported_apps="libreoffice"

additional_packages="qpdfview"
exported_apps="qpdfview"

additional_packages="gimp"
exported_apps="gimp"

additional_packages="drawing"
exported_apps="drawing"

additional_packages="vlc"
exported_apps="vlc"
# ------------------------------------------------------------------------------
# ==============================================================================
