# ------------------------------------------------------------------------------
[common-flags]
# 모든 컨테이너에 적용될 기본 설정
init=false
# pull=true
start_now=true
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# [debbox]
# image=docker.io/library/debian:latest
# include="common-flags"

# 미러 서버 변경 (가장 빠른 아주대 미러)
# pre_init_hooks="sed -i 's/deb.debian.org/ftp.kr.debian.org/g' /etc/apt/sources.list.d/debian.sources"
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# [fedobox]
# image=docker.io/library/fedora:latest
# include="common-flags"
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
[archbox]
image=docker.io/library/archlinux:latest
include="common-flags"
# ------------------------------------------------------------------------------
